-- Title sort for KOReader File Manager (series-aware + reading status)
-- Place this file in: .koreader/patches/
--
-- Adds two "Sort by" keys:
--   - title (series-aware)          [v2, inchangé]
--   - reading status + series-aware [nouveau]
--
-- Behavior of "reading status + series-aware":
--   Group 1 — Reading  : books currently being read, sorted by % read descending (100→0)
--   Group 2 — Unread   : never opened books, sorted by series+index / title
--   Group 3 — Complete : finished books, sorted by series+index / title
--
-- Within groups 2 & 3, sort key:
--   - If a book has a series (non-nil, non-empty, not " "):
--       primary = series name, secondary = series_index, tertiary = title
--   - Otherwise: sorted by title
--
-- Series detection: nil, "\uFFFF", empty or whitespace-only → no series
-- (Handles the case where series = " " generated by metadata-from-filename systems)

local BookList = require("ui/widget/booklist")
local DocSettings = require("docsettings")
local ffiUtil = require("ffi/util")
local _ = require("gettext")

local FFFF = "\u{FFFF}"

-- Reading status group constants (lower = displayed first)
local GROUP_READING  = 1
local GROUP_UNREAD   = 2
local GROUP_COMPLETE = 3

-- ─── Helpers shared by both collates ────────────────────────────────────────

local function hasSeries(props)
    if not props or not props.series then return false end
    if props.series == FFFF then return false end
    if tostring(props.series):match("^%s*$") then return false end
    return true
end

local function prepareItem(item, ui)
    if not ui or not ui.bookinfo then
        item.doc_props = {
            series        = FFFF,
            series_index  = nil,
            display_title = item.text,
        }
        return
    end
    local doc_props = ui.bookinfo:getDocProps(item.path or item.file)
    doc_props.series        = doc_props.series or FFFF
    doc_props.display_title = doc_props.display_title or item.text
    item.doc_props = doc_props
end

-- Returns GROUP_READING / GROUP_UNREAD / GROUP_COMPLETE and percent (0-100)
local function getReadingStatus(item)
    local path = item.path or item.file
    if not path then
        return GROUP_UNREAD, 0
    end

    local ok, doc_settings = pcall(DocSettings.open, DocSettings, path)
    if not ok or not doc_settings then
        return GROUP_UNREAD, 0
    end

    local summary = doc_settings:readSetting("summary")
    local status  = summary and summary.status or nil

    -- "complete" → finished
    if status == "complete" then
        doc_settings:close()
        return GROUP_COMPLETE, 100
    end

    -- Retrieve percent read from bookmarks/statistics
    local percent = 0
    local stats = doc_settings:readSetting("stats")
    if stats and stats.percent_finished then
        percent = math.floor(stats.percent_finished * 100 + 0.5)
    end

    doc_settings:close()

    -- If percent > 0 (or status explicitly "reading") → in progress
    if status == "reading" or percent > 0 then
        return GROUP_READING, percent
    end

    return GROUP_UNREAD, 0
end

-- Series-aware comparison (used for groups 2 & 3)
local function compareSeriesAware(a, b)
    local a_has = hasSeries(a.doc_props)
    local b_has = hasSeries(b.doc_props)

    local ka = a_has and a.doc_props.series or a.doc_props.display_title
    local kb = b_has and b.doc_props.series or b.doc_props.display_title

    if ka ~= kb then
        return ffiUtil.strcoll(ka, kb)
    end

    -- Same series → order by index then title
    if a_has and b_has and a.doc_props.series == b.doc_props.series then
        if a.doc_props.series_index and b.doc_props.series_index and
           a.doc_props.series_index ~= b.doc_props.series_index then
            return a.doc_props.series_index < b.doc_props.series_index
        end
        return ffiUtil.strcoll(a.doc_props.display_title, b.doc_props.display_title)
    end

    -- Same title key but different items → stabilize by title then path
    local ta = a.doc_props.display_title or a.text or ""
    local tb = b.doc_props.display_title or b.text or ""
    if ta ~= tb then return ffiUtil.strcoll(ta, tb) end

    local pa = a.path or a.file or ""
    local pb = b.path or b.file or ""
    return ffiUtil.strcoll(pa, pb)
end

-- ─── Collate 1 : title (series-aware) — inchangé par rapport à v2 ────────────

BookList.collates.title_series_aware = {
    text        = _("title (series-aware)"),
    menu_order  = 8,
    can_collate_mixed = false,

    item_func = function(item, ui)
        prepareItem(item, ui)
    end,

    init_sort_func = function(cache)
        local my_cache = cache or {}
        return function(a, b)
            return compareSeriesAware(a, b)
        end, my_cache
    end,

    mandatory_func = function(item)
        if not item.doc_props then return "" end
        if hasSeries(item.doc_props) then
            if item.doc_props.series_index then
                return item.doc_props.series .. " #" .. item.doc_props.series_index
            end
            return item.doc_props.series
        end
        return ""
    end,
}

-- ─── Collate 2 : reading status + series-aware ───────────────────────────────

BookList.collates.reading_status_series_aware = {
    text        = _("reading status (series-aware)"),
    menu_order  = 9,
    can_collate_mixed = false,

    item_func = function(item, ui)
        prepareItem(item, ui)
        -- Cache reading status on the item to avoid re-reading DocSettings in sort
        local group, percent = getReadingStatus(item)
        item.reading_group   = group
        item.reading_percent = percent
    end,

    init_sort_func = function(cache)
        local my_cache = cache or {}
        return function(a, b)
            local ag = a.reading_group or GROUP_UNREAD
            local bg = b.reading_group or GROUP_UNREAD

            -- Different groups → group order wins
            if ag ~= bg then
                return ag < bg
            end

            -- Group 1 (reading): sort by % descending
            if ag == GROUP_READING then
                local ap = a.reading_percent or 0
                local bp = b.reading_percent or 0
                if ap ~= bp then
                    return ap > bp  -- descending
                end
                -- tie-break by series/title
                return compareSeriesAware(a, b)
            end

            -- Groups 2 & 3: series-aware sort
            return compareSeriesAware(a, b)
        end, my_cache
    end,

    mandatory_func = function(item)
        -- Show reading info for "reading" group, series info otherwise
        if item.reading_group == GROUP_READING then
            local pct = item.reading_percent or 0
            if item.doc_props and hasSeries(item.doc_props) then
                local s = item.doc_props.series
                local idx = item.doc_props.series_index
                local base = idx and (s .. " #" .. idx) or s
                return base .. "  " .. pct .. "%"
            end
            return pct .. "%"
        end
        if not item.doc_props then return "" end
        if hasSeries(item.doc_props) then
            if item.doc_props.series_index then
                return item.doc_props.series .. " #" .. item.doc_props.series_index
            end
            return item.doc_props.series
        end
        return ""
    end,
}

return BookList.collates
